2018.8.1

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,24 +1,18 @@
 #!/sbin/sh -x
 # Sysconfig Patcher Installer
-# VR25 @ xda-developers
+# (c) 2017-2018, VR25 @ xda-developers
+# License: GPL v3+
 
-# Detect whether in boot mode
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
-$BOOTMODE || id | grep -q 'uid=0' || BOOTMODE=true
+# detect whether in bootmode
+ps | grep zygote | grep -v grep >/dev/null && bootMode=true || bootMode=false
+$bootMode || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && bootMode=true
+$bootMode || id | grep -q 'uid=0' || bootMode=true
 
-# Add Magisk busybox to PATH
-$BOOTMODE && export PATH="/sbin/.core/busybox:/dev/magisk/bin:$PATH"
-
-# Default permissions
+# default perms
 umask 022
 
-##########################################################################################
-# Functions
-##########################################################################################
-
 ui_print() {
-  $BOOTMODE && echo -e "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
+  $bootMode && echo -e "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
 }
 
 grep_prop() {
@@ -32,24 +26,24 @@ grep_prop() {
 is_mounted() { mountpoint -q "$1"; }
 
 mount_image() {
-  ui_print "- Mounting $1 to $2"
-  [ -d "$2" ] || mkdir -p "$2"
-  if (! is_mounted $2); then
-    LOOPDEVICE=
-    for LOOP in 0 1 2 3 4 5 6 7; do
-      if (! is_mounted $2); then
-        LOOPDEVICE=/dev/block/loop$LOOP
-        [ -f "$LOOPDEVICE" ] || mknod $LOOPDEVICE b 7 $LOOP 2>/dev/null
-        losetup $LOOPDEVICE $1
-        if [ "$?" -eq "0" ]; then
-          mount -t ext4 -o loop $LOOPDEVICE $2
-          is_mounted $2 || /system/bin/toolbox mount -t ext4 -o loop $LOOPDEVICE $2
-          is_mounted $2 || /system/bin/toybox mount -t ext4 -o loop $LOOPDEVICE $2
-        fi
-        is_mounted $2 && break
-      fi
-    done
-  fi
+	ui_print "- Mounting $1 to $2"
+	[ -d "$2" ] || mkdir -p "$2"
+	if (! is_mounted $2); then
+		loopDevice=
+		for LOOP in 0 1 2 3 4 5 6 7; do
+			if (! is_mounted $2); then
+				loopDevice=/dev/block/loop$LOOP
+				[ -f "$loopDevice" ] || mknod $loopDevice b 7 $LOOP 2>/dev/null
+				losetup $loopDevice $1
+				if [ "$?" -eq "0" ]; then
+					mount -t ext4 -o loop $loopDevice $2
+					is_mounted $2 || /system/bin/toolbox mount -t ext4 -o loop $loopDevice $2
+					is_mounted $2 || /system/bin/toybox mount -t ext4 -o loop $loopDevice $2
+				fi
+				is_mounted $2 && break
+			fi
+		done
+	fi
 }
 
 set_perm() {
@@ -60,17 +54,11 @@ set_perm() {
 
 set_perm_recursive() {
   find "$1" -type d 2>/dev/null | while read dir; do
-    set_perm "$dir" $2 $3 $4 $6
+	set_perm "$dir" $2 $3 $4 $6
   done
   find "$1" -type f -o -type l 2>/dev/null | while read file; do
-    set_perm "$file" $2 $3 $5 $6
+	set_perm "$file" $2 $3 $5 $6
   done
-}
-
-mktouch() {
-  mkdir -p ${1%/*} 2>/dev/null
-  [ -z "$2" ] && touch "$1" || echo "$2" > "$1"
-  chmod 644 $1
 }
 
 request_size_check() {
@@ -92,88 +80,35 @@ image_size_check() {
   curSizeM=$((curSizeM * 4 / 1024))
 }
 
-resolve_link() {
-  RESOLVED="$1"
-  while RESOLVE=`readlink $RESOLVED`; do
-    RESOLVED=$RESOLVE
-  done
-  echo $RESOLVED
+mod_info() {
+  grep_prop "$1" $INSTALLER/module.prop
 }
 
-find_boot_image() {
-  BOOTIMAGE=
-  if [ ! -z $SLOT ]; then
-    BOOTIMAGE=`find /dev/block -iname boot$SLOT | head -n 1` 2>/dev/null
-  fi
-  if [ -z "$BOOTIMAGE" ]; then
-    # The slot info is incorrect...
-    SLOT=
-    for BLOCK in boot_a kern-a android_boot kernel boot lnx bootimg; do
-      BOOTIMAGE=`find /dev/block -iname $BLOCK | head -n 1` 2>/dev/null
-      [ ! -z $BOOTIMAGE ] && break
-    done
-  fi
-  # Recovery fallback
-  if [ -z "$BOOTIMAGE" ]; then
-    for FSTAB in /etc/*fstab*; do
-      BOOTIMAGE=`grep -v '#' $FSTAB | grep -E '/boot[^a-zA-Z]' | grep -oE '/dev/[a-zA-Z0-9_./-]*'`
-      [ ! -z $BOOTIMAGE ] && break
-    done
-  fi
-  [ ! -z "$BOOTIMAGE" ] && BOOTIMAGE=`resolve_link $BOOTIMAGE`
+print_modname() {
+  ui_print " "
+  ui_print "$(mod_info name) ($(mod_info id)) $(mod_info version)"
+  ui_print "$(mod_info author)"
+  ui_print "Powered by Magisk (@topjohnwu)"
+  ui_print " "
 }
 
-find_dtbo_image() {
-  DTBOIMAGE=`find /dev/block -iname dtbo$SLOT | head -n 1` 2>/dev/null
-  [ ! -z $DTBOIMAGE ] && DTBOIMAGE=`resolve_link $DTBOIMAGE`
+set_permissions() {
+  # Only some special files require specific permissions
+  # The default permissions should be good enough for most cases
+
+  # Here are some examples for the set_perm functions:
+
+  # set_perm_recursive  <dirname>                <owner> <group> <dirpermission> <filepermission> <contexts> (default: u:object_r:system_file:s0)
+  # set_perm_recursive  $modPath/system/lib       0       0       0755            0644
+
+  # set_perm  <filename>                         <owner> <group> <permission> <contexts> (default: u:object_r:system_file:s0)
+  # set_perm  $modPath/system/bin/app_process32   0       2000    0755         u:object_r:zygote_exec:s0
+  # set_perm  $modPath/system/bin/dex2oat         0       2000    0755         u:object_r:dex2oat_exec:s0
+  # set_perm  $modPath/system/lib/libart.so       0       0       0644
+
+  # The following is default permissions, DO NOT remove
+  set_perm_recursive  $tmpModPath  0  0  0755  0755
 }
-
-
-mount_partitions() {
-  mount /data 2>/dev/null
-  mount /cache 2>/dev/null
-
-  # Check A/B slot
-  SLOT=`getprop ro.boot.slot_suffix`
-  if [ -z $SLOT ]; then
-    SLOT=_`getprop ro.boot.slot`
-    [ $SLOT = "_" ] && SLOT=
-  fi
-
-  # Check the boot image to make sure the slot actually make sense
-  find_boot_image
-  find_dtbo_image
-  [ -z $SLOT ] || ui_print "- A/B partition detected, current slot: $SLOT"
-
-  ui_print "- Mounting /system, /vendor"
-  is_mounted /system || [ -f /system/build.prop ] || mount -o ro /system 2>/dev/null
-  if ! is_mounted /system && ! [ -f /system/build.prop ]; then
-    SYSTEMBLOCK=`find /dev/block -iname system$SLOT | head -n 1`
-    mount -t ext4 -o ro $SYSTEMBLOCK /system
-  fi
-  is_mounted /system || [ -f /system/build.prop ] || abort "! Cannot mount /system"
-  cat /proc/mounts | grep -E '/dev/root|/system_root' >/dev/null && SKIP_INITRAMFS=true || SKIP_INITRAMFS=false
-  if [ -f /system/init.rc ]; then
-    SKIP_INITRAMFS=true
-    mkdir /system_root 2>/dev/null
-    mount --move /system /system_root
-    mount -o bind /system_root/system /system
-  fi
-  $SKIP_INITRAMFS && ui_print "- Device skip_initramfs detected"
-  if [ -L /system/vendor ]; then
-    # Seperate /vendor partition
-    is_mounted /vendor || mount -o ro /vendor 2>/dev/null
-    if ! is_mounted /vendor; then
-      VENDORBLOCK=`find /dev/block -iname vendor$SLOT | head -n 1`
-      mount -t ext4 -o ro $VENDORBLOCK /vendor
-    fi
-    is_mounted /vendor || abort "! Cannot mount /vendor"
-  fi
-}
-
-##########################################################################################
-# Flashable update-binary preparation
-##########################################################################################
 
 OUTFD=$2
 ZIP="$3"
@@ -183,164 +118,62 @@ if [ "$?" -eq "0" ]; then
   OUTFD=0
 
   for FD in `ls /proc/$$/fd`; do
-    readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
-    if [ "$?" -eq "0" ]; then
-      ps | grep " 3 $FD " | grep -v grep >/dev/null
-      if [ "$?" -eq "0" ]; then
-        OUTFD=$FD
-        break
-      fi
-    fi
+	readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
+	if [ "$?" -eq "0" ]; then
+	  ps | grep " 3 $FD " | grep -v grep >/dev/null
+	  if [ "$?" -eq "0" ]; then
+		OUTFD=$FD
+		break
+	  fi
+	fi
   done
 fi
 
-# This path should work in any cases
-TMPDIR=/dev/tmp
-
-INSTALLER=$TMPDIR/install
-MOUNTPATH=$TMPDIR/magisk_img
-$BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
-[ -d /data/adb/magisk ] && IMG=/data/adb/$IMGNAME || IMG=/data/$IMGNAME
+tmpDir=/dev/tmp
+INSTALLER=$tmpDir/install
+mountPath=$tmpDir/magisk_img
+$bootMode && imgName=magisk_merge.img || imgName=magisk.img
+[ -d /data/adb/magisk ] && IMG=/data/adb/$imgName || IMG=/data/$imgName
 
 if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
 	ui_print " "
-	ui_print "(!) No Magisk installation found or installed version not supported"
+	ui_print "(!) No Magisk installation found or installed version is not supported"
 	ui_print " "
 	exit 1
 fi
 
-# Initial cleanup
-rm -rf $TMPDIR 2>/dev/null
+# initial cleanup
+rm -rf $tmpDir 2>/dev/null
 mkdir -p $INSTALLER 2>/dev/null
 
 unzip -o "$ZIP" 'common/*' module.prop -d $INSTALLER >&2
 
-MODID="`grep_prop id $INSTALLER/module.prop`"
-TMP_MODPATH=$MOUNTPATH/$MODID
-MODPATH=$TMP_MODPATH
+modID="`grep_prop id $INSTALLER/module.prop`"
+tmpModPath=$mountPath/$modID
+modPath=$tmpModPath
 
-# Find MODPATH
-if $BOOTMODE; then
-  for MountPoint in /sbin/.core/img /magisk; do
-    if [ -d "$MountPoint/.core" ] || [ -d "$MountPoint/lost+found" ]; then
-      MountPoint=$MountPoint
-      MODPATH=$MountPoint/$MODID
-      mkdir -p $MODPATH 2>/dev/null
+# find modPath
+if $bootMode; then
+  for mountPoint in /sbin/.core/img /magisk; do
+    if [ -d "$mountPoint/.core" ] || [ -d "$mountPoint/lost+found" ]; then
+      mountPoint=$mountPoint
+      modPath=$mountPoint/$modID
+      mkdir -p $modPath 2>/dev/null
       break
     fi
   done
-
-	if [ ! -d "$MODPATH" ]; then
-		echo -e "(!) Magisk mount point not found"
-		exit 1
-	fi
-
-  if ! is_mounted $MountPoint; then
-    ui_print "(!) Magisk is not activated!... abort"
-    exit 1
-  fi
+  [[ -d $modPath ]] || { echo -e "\n(!) Magisk mount point not found\n"; exit 1; }
+  is_mounted $mountPoint || { echo -e "\n(!) Magisk is not activated!... abort\n"; exit 1; }
 fi
-
-##########################################################################################
-# Configs
-##########################################################################################
-
-# Set to true if you need to enable Magic Mount
-# Most mods would like it to be enabled
-AUTOMOUNT=true
-
-# Set to true if you need to load system.prop
-PROPFILE=false
-
-# Set to true if you need post-fs-data script
-POSTFSDATA=true
-
-# Set to true if you need late_start service script
-LATESTARTSERVICE=false
-
-ModVersion="`grep_prop version $INSTALLER/module.prop`"
-print_modname() {
-  ui_print "******************************"
-  ui_print "Sysconfig Patcher $ModVersion"
-  ui_print "    VR25 @ xda-developers    "
-  ui_print "******************************"
-}
-
-# List all directories you want to directly replace in the system
-# Check the documentations for more info about how Magic Mount works, and why you need this
-
-# This is an example
-REPLACE="
-/system/app/Youtube
-/system/priv-app/SystemUI
-/system/priv-app/Settings
-/system/framework
-"
-
-# Construct your own list here, it will override the example above
-# !DO NOT! remove this if you don't need to replace anything, leave it empty as it is now
-REPLACE="
-"
-
-set_permissions() {
-  # Only some special files require specific permissions
-  # The default permissions should be good enough for most cases
-
-  # Here are some examples for the set_perm functions:
-
-  # set_perm_recursive  <dirname>                <owner> <group> <dirpermission> <filepermission> <contexts> (default: u:object_r:system_file:s0)
-  # set_perm_recursive  $MODPATH/system/lib       0       0       0755            0644
-
-  # set_perm  <filename>                         <owner> <group> <permission> <contexts> (default: u:object_r:system_file:s0)
-  # set_perm  $MODPATH/system/bin/app_process32   0       2000    0755         u:object_r:zygote_exec:s0
-  # set_perm  $MODPATH/system/bin/dex2oat         0       2000    0755         u:object_r:dex2oat_exec:s0
-  # set_perm  $MODPATH/system/lib/libart.so       0       0       0644
-
-  # The following is default permissions, DO NOT remove
-  set_perm_recursive  $TMP_MODPATH  0  0  0755  0644
-}
-
-##########################################################################################
-# Main
-##########################################################################################
 
 # Print mod name
 print_modname
 
-# Please leave this message in your flashable zip for credits :)
-ui_print "******************************"
-ui_print "Powered by Magisk (@topjohnwu)"
-ui_print "******************************"
-
-mount_partitions
-
-API=`grep_prop ro.build.version.sdk`
-ABI=`grep_prop ro.product.cpu.abi | cut -c-3`
-ABI2=`grep_prop ro.product.cpu.abi2 | cut -c-3`
-ABILONG=`grep_prop ro.product.cpu.abi`
-
-ARCH=arm
-IS64BIT=false
-if [ "$ABI" = "x86" ]; then ARCH=x86; fi;
-if [ "$ABI2" = "x86" ]; then ARCH=x86; fi;
-if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; IS64BIT=true; fi;
-if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; IS64BIT=true; fi;
-
-# You can get the Android API version from $API, the CPU architecture from $ARCH
-# Useful if you are creating Android version / platform dependent mods
-
-if ! is_mounted /data; then
-  IMG=/cache/$IMGNAME
-  ui_print " "
-  ui_print "***********************************"
-  ui_print "*      !! Data unavailable !!     *"
-  ui_print "* Magisk detection is impossible  *"
-  ui_print "* Installation will still proceed *"
-  ui_print "*  But please make sure you have  *"
-  ui_print "*        Magisk installed!!       *"
-  ui_print "***********************************"
-  ui_print " "
-fi
+$bootMode || ui_print "- Mounting partitions"
+mount -o ro /system 2>/dev/null
+mount -o ro /vendor 2>/dev/null
+mount /data 2>/dev/null
+mount /cache 2>/dev/null
 
 request_zip_size_check "$ZIP"
 
@@ -348,9 +181,9 @@ if [ -f "$IMG" ]; then
   ui_print "- $IMG detected!"
   image_size_check $IMG
   if [ "$reqSizeM" -gt "$curFreeM" ]; then
-    SIZE=$(((reqSizeM + curUsedM) / 32 * 32 + 64))
-    ui_print "- Resizing $IMG to ${SIZE}M..."
-    resize2fs $IMG ${SIZE}M >&2
+	SIZE=$(((reqSizeM + curUsedM) / 32 * 32 + 64))
+	ui_print "- Resizing $IMG to ${SIZE}M..."
+	resize2fs $IMG ${SIZE}M >&2
   fi
 else
   SIZE=$((reqSizeM / 32 * 32 + 64));
@@ -358,102 +191,51 @@ else
   make_ext4fs -l ${SIZE}M $IMG >&2
 fi
 
-mount_image $IMG $MOUNTPATH
-if ! is_mounted $MOUNTPATH; then
+mount_image $IMG $mountPath
+if ! is_mounted $mountPath; then
+  ui_print " "
   ui_print "(!) $IMG mount failed... abort"
+  ui_print " "
   exit 1
 fi
 
 ##########################################################################################
-# Module space
+# module-specific code
 ##########################################################################################
 
-SysPaths="/sbin/.core/mirror/system
-/dev/magisk/mirror/system
-/system"
+# create module paths
+rm -rf $tmpModPath 2>/dev/null
+mkdir -p $tmpModPath
+  
+# extract module files
+ui_print "- Extracting module files"
+unzip -o "$ZIP" -d $INSTALLER >&2
+cd $INSTALLER
+mv common/* $tmpModPath/
 
-for p in $SysPaths; do
-	if [ $p/build.prop ]; then
-		cp -R $p/etc/sysconfig $INSTALLER
-		SysPath="$p"
-		break
-	fi
-done
-
-# Detect MagicGApps
-FoundMGA="$(find $MOUNTPATH /sbin/.core/img /magisk -type d -name MagicGApps 2>/dev/null | head -n1)"
-echo "$FoundMGA" | grep -q '/MagicGApps$' && cp -a "$FoundMGA"/etc/sysconfig/* $INSTALLER/system/etc/sysconfig 2>/dev/null
-
-# Create mod paths
-rm -rf $TMP_MODPATH 2>/dev/null
-mkdir -p $TMP_MODPATH/system/etc
-
-# Patch /system/etc/sysconfig/* for data and battery savings
-for file in $INSTALLER/sysconfig/*; do
-	if [ -f "$file" ]; then
-		if grep -Eq '<allow-in-power-save|<allow-in-data-usage-save' "$file"; then
-			sed -i '/allow-in-.*-save/s/<a/<!-- a/' $file
-		else
-			rm "$file"
-		fi
-	fi
-done
-sed -i '/.volta/s/<!-- a/<a/' $INSTALLER/sysconfig/google.xml
-
-mv $INSTALLER/sysconfig $TMP_MODPATH/system/etc/
-
-# Export /system size info for automatic re-patching across ROM/GApps updates
-du -s $SysPath | cut -f1 >$TMP_MODPATH/.SystemSizeK
+# auto-mount folders
+touch $tmpModPath/auto_mount
 
 ##########################################################################################
 
-# Handle replace folders
-for TARGET in $REPLACE; do
-  mktouch $TMP_MODPATH$TARGET/.replace
-done
+# module info
+cp $INSTALLER/module.prop $tmpModPath/
 
-# Auto Mount
-if $AUTOMOUNT; then
-  mktouch $TMP_MODPATH/auto_mount
-fi
-
-# prop files
-if $PROPFILE; then
-  cp -af $INSTALLER/common/system.prop $TMP_MODPATH/system.prop
-fi
-
-# Module info
-cp -af $INSTALLER/module.prop $TMP_MODPATH/module.prop
-if $BOOTMODE; then
-  # Update info for Magisk Manager
-  mktouch $MODPATH/update
-  cp -af $INSTALLER/module.prop $MODPATH/module.prop
-fi
-
-# post-fs-data mode scripts
-if $POSTFSDATA; then
-  cp -af $INSTALLER/common/post-fs-data.sh $TMP_MODPATH/post-fs-data.sh
-fi
-
-# service mode scripts
-if $LATESTARTSERVICE; then
-  cp -af $INSTALLER/common/service.sh $TMP_MODPATH/service.sh
+# update info for Magisk Manager
+if $bootMode; then
+  touch $modPath/update
+  cp $INSTALLER/module.prop $modPath/
 fi
 
 ui_print "- Setting permissions"
 set_permissions
 
-$BOOTMODE || ui_print "- Unmounting partitions"
-umount $MOUNTPATH
-losetup -d $LOOPDEVICE
-rmdir $MOUNTPATH
-if ! $BOOTMODE; then
-	umount -l /system_root 2>/dev/null
-	umount -l /system 2>/dev/null
-	umount -l /vendor 2>/dev/null
-fi
+$bootMode || ui_print "- Unmounting partitions"
+umount $mountPath
+losetup -d $loopDevice
+rmdir $mountPath
 
-# Shrink the image if possible
+# shrink the image if possible
 image_size_check $IMG
 NEWDATASIZE=$((curUsedM / 32 * 32 + 32))
 if [ "$curSizeM" -gt "$NEWDATASIZE" ]; then
@@ -461,5 +243,11 @@ if [ "$curSizeM" -gt "$NEWDATASIZE" ]; then
   resize2fs $IMG ${NEWDATASIZE}M >&2
 fi
 
-ui_print "- Done"
+if ! $bootMode; then
+  umount /system
+  umount /vendor 2>/dev/null
+fi
+
+ui_print "- End"
+ui_print " "
 exit 0
